// cpp_init.h — explicitly declare static ctors so we can call them from E32Main.
// These are C-linkage symbols generated by the compiler.

extern "C" void _GLOBAL__I_gEglDisplay();
extern "C" void _GLOBAL__I__ZN4Sexy5Color5BlackE();
extern "C" void _GLOBAL__I_gShownMoreSunTutorial();
extern "C" void _GLOBAL__I_gPlantDefs();
extern "C" void _GLOBAL__I_gZombieDefs();
extern "C" void _GLOBAL__I_gProjectileDefinition();
extern "C" void _GLOBAL__I__ZN4CoinC2Ev();
extern "C" void _GLOBAL__I__ZN9LawnMower19LawnMowerInitializeEi();
extern "C" void _GLOBAL__I__ZN8GridItemC2Ev();
extern "C" void _GLOBAL__I_gZombieWaves();
extern "C" void _GLOBAL__I_gIsPartnerBuild();
