/* Derived from src/Resources.cpp
* Copyright (C) 2026 Zhou Qiankang <wszqkzqk@qq.com>
 *
 * SPDX-License-Identifier: LGPL-3.0-or-later
 *
 * This file is part of PvZ-Portable.
*/
#ifndef __RESOURCES_H__
#define __RESOURCES_H__
// AUTO-GENERATED to match src/Resources.cpp. ResourceManager is GLOBAL
// (engine/ResourceManager.h); do not redeclare it in namespace Sexy.
#include <e32def.h>
#include "engine/Image.h"
#include "engine/ResourceManager.h"

namespace Sexy {

// ---- ResourceId enum (generated from gResources[] order; 317 entries) ----
enum ResourceId
{
	IMAGE_BACKGROUND1_ID,
	IMAGE_BACKGROUND1_GAMEOVER_INTERIOR_OVERLAY_ID,
	IMAGE_BACKGROUND1_GAMEOVER_MASK_ID,
	IMAGE_BACKGROUND1UNSODDED_ID,
	IMAGE_SOD1ROW_ID,
	IMAGE_SOD3ROW_ID,
	IMAGE_BACKGROUND2_ID,
	IMAGE_BACKGROUND2_GAMEOVER_INTERIOR_OVERLAY_ID,
	IMAGE_BACKGROUND2_GAMEOVER_MASK_ID,
	IMAGE_BACKGROUND3_ID,
	IMAGE_BACKGROUND3_GAMEOVER_INTERIOR_OVERLAY_ID,
	IMAGE_BACKGROUND3_GAMEOVER_MASK_ID,
	IMAGE_BACKGROUND4_ID,
	IMAGE_BACKGROUND4_GAMEOVER_INTERIOR_OVERLAY_ID,
	IMAGE_BACKGROUND4_GAMEOVER_MASK_ID,
	IMAGE_FOG_ID,
	IMAGE_FOG_SOFTWARE_ID,
	IMAGE_BACKGROUND5_ID,
	IMAGE_BACKGROUND5_GAMEOVER_MASK_ID,
	IMAGE_BACKGROUND6BOSS_ID,
	IMAGE_BACKGROUND6_GAMEOVER_MASK_ID,
	IMAGE_BACKGROUND_MUSHROOMGARDEN_ID,
	IMAGE_BACKGROUND_GREENHOUSE_ID,
	IMAGE_BACKGROUND_GREENHOUSE_OVERLAY_ID,
	IMAGE_AQUARIUM1_ID,
	IMAGE_WAVECENTER_ID,
	IMAGE_WAVESIDE_ID,
	IMAGE_AWARDSCREEN_BACK_ID,
	IMAGE_CHALLENGE_BACKGROUND_ID,
	IMAGE_CHALLENGE_WINDOW_ID,
	IMAGE_CHALLENGE_WINDOW_HIGHLIGHT_ID,
	IMAGE_CHALLENGE_BLANK_ID,
	IMAGE_CHALLENGE_THUMBNAILS_ID,
	IMAGE_SURVIVAL_THUMBNAILS_ID,
	IMAGE_LOCK_ID,
	IMAGE_LOCK_OPEN_ID,
	IMAGE_ALMANAC_INDEXBACK_ID,
	IMAGE_ALMANAC_PLANTBACK_ID,
	IMAGE_ALMANAC_ZOMBIEBACK_ID,
	IMAGE_ALMANAC_PLANTCARD_ID,
	IMAGE_ALMANAC_ZOMBIECARD_ID,
	IMAGE_ALMANAC_ZOMBIEWINDOW_ID,
	IMAGE_ALMANAC_ZOMBIEWINDOW2_ID,
	IMAGE_ALMANAC_ZOMBIEBLANK_ID,
	IMAGE_ALMANAC_GROUNDDAY_ID,
	IMAGE_ALMANAC_GROUNDNIGHT_ID,
	IMAGE_ALMANAC_GROUNDPOOL_ID,
	IMAGE_ALMANAC_GROUNDNIGHTPOOL_ID,
	IMAGE_ALMANAC_GROUNDROOF_ID,
	IMAGE_ALMANAC_GROUNDICE_ID,
	IMAGE_ALMANAC_CLOSEBUTTON_ID,
	IMAGE_ALMANAC_CLOSEBUTTONHIGHLIGHT_ID,
	IMAGE_ALMANAC_INDEXBUTTON_ID,
	IMAGE_ALMANAC_INDEXBUTTONHIGHLIGHT_ID,
	IMAGE_STORE_BACKGROUND_ID,
	IMAGE_STORE_BACKGROUNDNIGHT_ID,
	IMAGE_STORE_CAR_ID,
	IMAGE_STORE_CAR_NIGHT_ID,
	IMAGE_STORE_CARCLOSED_ID,
	IMAGE_STORE_CARCLOSED_NIGHT_ID,
	IMAGE_STORE_HATCHBACKOPEN_ID,
	IMAGE_STORE_SIGN_ID,
	IMAGE_STORE_MAINMENUBUTTON_ID,
	IMAGE_STORE_MAINMENUBUTTONDOWN_ID,
	IMAGE_STORE_MAINMENUBUTTONHIGHLIGHT_ID,
	IMAGE_STORE_NEXTBUTTON_ID,
	IMAGE_STORE_NEXTBUTTONHIGHLIGHT_ID,
	IMAGE_STORE_NEXTBUTTONDISABLED_ID,
	IMAGE_STORE_PREVBUTTON_ID,
	IMAGE_STORE_PREVBUTTONHIGHLIGHT_ID,
	IMAGE_STORE_PREVBUTTONDISABLED_ID,
	IMAGE_STORE_PRICETAG_ID,
	IMAGE_STORE_PACKETUPGRADE_ID,
	IMAGE_STORE_MUSHROOMGARDENICON_ID,
	IMAGE_STORE_AQUARIUMGARDENICON_ID,
	IMAGE_STORE_TREEOFWISDOMICON_ID,
	IMAGE_STORE_FIRSTAIDWALLNUTICON_ID,
	IMAGE_STORE_PVZICON_ID,
	IMAGE_ZOMBIE_NOTE_ID,
	IMAGE_ZOMBIE_NOTE1_ID,
	IMAGE_ZOMBIE_NOTE2_ID,
	IMAGE_ZOMBIE_NOTE3_ID,
	IMAGE_ZOMBIE_NOTE4_ID,
	IMAGE_ZOMBIE_FINAL_NOTE_ID,
	IMAGE_ZOMBIE_NOTE_HELP_ID,
	FONT_BRIANNETOD32_ID,
	FONT_BRIANNETOD32BLACK_ID,
	IMAGE_REANIM_SUNFLOWER_HEAD_SING1_ID,
	IMAGE_REANIM_SUNFLOWER_HEAD_SING2_ID,
	IMAGE_REANIM_SUNFLOWER_HEAD_SING3_ID,
	IMAGE_REANIM_SUNFLOWER_HEAD_SING4_ID,
	IMAGE_REANIM_SUNFLOWER_HEAD_SING5_ID,
	IMAGE_REANIM_SUNFLOWER_HEAD_WINK_ID,
	IMAGE_REANIM_CREDITS_DISCOLIGHTS_ID,
	IMAGE_REANIM_CREDITS_FOGMACHINE_ID,
	IMAGE_CREDITS_ZOMBIENOTE_ID,
	IMAGE_CREDITS_PLAYBUTTON_ID,
	IMAGE_ZOMBATAR_ACCESSORY_BG_ID,
	IMAGE_ZOMBATAR_PREV_BUTTON_ID,
	IMAGE_ZOMBATAR_PREV_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_NEXT_BUTTON_ID,
	IMAGE_ZOMBATAR_NEXT_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_ZOMBIE_BLANK_ID,
	IMAGE_ZOMBATAR_ZOMBIE_BLANK_SKIN_ID,
	IMAGE_ZOMBATAR_BACKGROUND_CRAZYDAVE_ID,
	IMAGE_ZOMBATAR_BACKGROUND_MENU_ID,
	IMAGE_ZOMBATAR_BACKGROUND_MENU_DOS_ID,
	IMAGE_ZOMBATAR_BACKGROUND_ROOF_ID,
	IMAGE_ZOMBATAR_WIDGET_BG_ID,
	IMAGE_ZOMBATAR_WIDGET_INNER_BG_ID,
	IMAGE_ZOMBATAR_COLORS_BG_ID,
	IMAGE_ZOMBATAR_LOGO_ID,
	IMAGE_ZOMBATAR_ACCESSORY_BUTTON_ID,
	IMAGE_ZOMBATAR_ACCESSORY_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_ACCESSORY_BUTTON_OVER_ID,
	IMAGE_ZOMBATAR_BACKDROPS_BUTTON_ID,
	IMAGE_ZOMBATAR_BACKDROPS_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_BACKDROPS_BUTTON_OVER_ID,
	IMAGE_ZOMBATAR_CLOTHES_BUTTON_ID,
	IMAGE_ZOMBATAR_CLOTHES_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_CLOTHES_BUTTON_OVER_ID,
	IMAGE_ZOMBATAR_EYEWEAR_BUTTON_ID,
	IMAGE_ZOMBATAR_EYEWEAR_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_EYEWEAR_BUTTON_OVER_ID,
	IMAGE_ZOMBATAR_FACIAL_HAIR_BUTTON_ID,
	IMAGE_ZOMBATAR_FACIAL_HAIR_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_FACIAL_HAIR_BUTTON_OVER_ID,
	IMAGE_ZOMBATAR_HAIR_BUTTON_ID,
	IMAGE_ZOMBATAR_HAIR_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_HAIR_BUTTON_OVER_ID,
	IMAGE_ZOMBATAR_HATS_BUTTON_ID,
	IMAGE_ZOMBATAR_HATS_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_HATS_BUTTON_OVER_ID,
	IMAGE_ZOMBATAR_SKIN_BUTTON_ID,
	IMAGE_ZOMBATAR_SKIN_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_TIDBITS_BUTTON_ID,
	IMAGE_ZOMBATAR_TIDBITS_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_TIDBITS_BUTTON_OVER_ID,
	IMAGE_ZOMBATAR_ACCESSORY_BG_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_TRIPTYCH_ID,
	IMAGE_ZOMBATAR_COLORPICKER_ID,
	IMAGE_ZOMBATAR_COLORPICKER_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_COLORPICKER_NONE_ID,
	IMAGE_ZOMBATAR_ACCESSORY_BG_NONE_ID,
	IMAGE_ZOMBATAR_COLORS_BG_SMALL_ID,
	IMAGE_ZOMBATAR_CLOTHES_1_ID,
	IMAGE_ZOMBATAR_CLOTHES_2_ID,
	IMAGE_ZOMBATAR_CLOTHES_3_ID,
	IMAGE_ZOMBATAR_CLOTHES_4_ID,
	IMAGE_ZOMBATAR_CLOTHES_5_ID,
	IMAGE_ZOMBATAR_CLOTHES_6_ID,
	IMAGE_ZOMBATAR_CLOTHES_7_ID,
	IMAGE_ZOMBATAR_CLOTHES_8_ID,
	IMAGE_ZOMBATAR_CLOTHES_9_ID,
	IMAGE_ZOMBATAR_CLOTHES_10_ID,
	IMAGE_ZOMBATAR_CLOTHES_11_ID,
	IMAGE_ZOMBATAR_CLOTHES_12_ID,
	IMAGE_ZOMBATAR_HATS_1_ID,
	IMAGE_ZOMBATAR_HATS_2_ID,
	IMAGE_ZOMBATAR_HATS_3_ID,
	IMAGE_ZOMBATAR_HATS_4_ID,
	IMAGE_ZOMBATAR_HATS_5_ID,
	IMAGE_ZOMBATAR_HATS_6_ID,
	IMAGE_ZOMBATAR_HATS_7_ID,
	IMAGE_ZOMBATAR_HATS_8_ID,
	IMAGE_ZOMBATAR_HATS_9_ID,
	IMAGE_ZOMBATAR_HATS_10_ID,
	IMAGE_ZOMBATAR_HATS_11_ID,
	IMAGE_ZOMBATAR_HATS_12_ID,
	IMAGE_ZOMBATAR_HATS_13_ID,
	IMAGE_ZOMBATAR_HATS_14_ID,
	IMAGE_ZOMBATAR_HAIR_1_ID,
	IMAGE_ZOMBATAR_HAIR_2_ID,
	IMAGE_ZOMBATAR_HAIR_3_ID,
	IMAGE_ZOMBATAR_HAIR_4_ID,
	IMAGE_ZOMBATAR_HAIR_5_ID,
	IMAGE_ZOMBATAR_HAIR_6_ID,
	IMAGE_ZOMBATAR_HAIR_7_ID,
	IMAGE_ZOMBATAR_HAIR_8_ID,
	IMAGE_ZOMBATAR_HAIR_9_ID,
	IMAGE_ZOMBATAR_HAIR_10_ID,
	IMAGE_ZOMBATAR_HAIR_11_ID,
	IMAGE_ZOMBATAR_HAIR_12_ID,
	IMAGE_ZOMBATAR_HAIR_13_ID,
	IMAGE_ZOMBATAR_HAIR_14_ID,
	IMAGE_ZOMBATAR_HAIR_15_ID,
	IMAGE_ZOMBATAR_HAIR_16_ID,
	IMAGE_ZOMBATAR_EYEWEAR_1_ID,
	IMAGE_ZOMBATAR_EYEWEAR_2_ID,
	IMAGE_ZOMBATAR_EYEWEAR_3_ID,
	IMAGE_ZOMBATAR_EYEWEAR_4_ID,
	IMAGE_ZOMBATAR_EYEWEAR_5_ID,
	IMAGE_ZOMBATAR_EYEWEAR_6_ID,
	IMAGE_ZOMBATAR_EYEWEAR_7_ID,
	IMAGE_ZOMBATAR_EYEWEAR_8_ID,
	IMAGE_ZOMBATAR_EYEWEAR_9_ID,
	IMAGE_ZOMBATAR_EYEWEAR_10_ID,
	IMAGE_ZOMBATAR_EYEWEAR_11_ID,
	IMAGE_ZOMBATAR_EYEWEAR_12_ID,
	IMAGE_ZOMBATAR_EYEWEAR_13_ID,
	IMAGE_ZOMBATAR_EYEWEAR_14_ID,
	IMAGE_ZOMBATAR_EYEWEAR_15_ID,
	IMAGE_ZOMBATAR_EYEWEAR_16_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_1_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_2_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_3_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_4_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_5_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_6_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_7_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_8_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_9_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_10_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_11_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_12_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_13_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_14_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_15_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_16_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_17_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_18_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_19_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_20_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_21_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_22_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_23_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_24_ID,
	IMAGE_ZOMBATAR_TIDBITS_1_ID,
	IMAGE_ZOMBATAR_TIDBITS_2_ID,
	IMAGE_ZOMBATAR_TIDBITS_3_ID,
	IMAGE_ZOMBATAR_TIDBITS_4_ID,
	IMAGE_ZOMBATAR_TIDBITS_5_ID,
	IMAGE_ZOMBATAR_TIDBITS_6_ID,
	IMAGE_ZOMBATAR_TIDBITS_7_ID,
	IMAGE_ZOMBATAR_TIDBITS_8_ID,
	IMAGE_ZOMBATAR_TIDBITS_9_ID,
	IMAGE_ZOMBATAR_TIDBITS_10_ID,
	IMAGE_ZOMBATAR_TIDBITS_11_ID,
	IMAGE_ZOMBATAR_TIDBITS_12_ID,
	IMAGE_ZOMBATAR_TIDBITS_13_ID,
	IMAGE_ZOMBATAR_TIDBITS_14_ID,
	IMAGE_ZOMBATAR_ACCESSORY_1_ID,
	IMAGE_ZOMBATAR_ACCESSORY_2_ID,
	IMAGE_ZOMBATAR_ACCESSORY_3_ID,
	IMAGE_ZOMBATAR_ACCESSORY_4_ID,
	IMAGE_ZOMBATAR_ACCESSORY_5_ID,
	IMAGE_ZOMBATAR_ACCESSORY_6_ID,
	IMAGE_ZOMBATAR_ACCESSORY_7_ID,
	IMAGE_ZOMBATAR_ACCESSORY_8_ID,
	IMAGE_ZOMBATAR_ACCESSORY_9_ID,
	IMAGE_ZOMBATAR_ACCESSORY_10_ID,
	IMAGE_ZOMBATAR_ACCESSORY_11_ID,
	IMAGE_ZOMBATAR_ACCESSORY_12_ID,
	IMAGE_ZOMBATAR_ACCESSORY_13_ID,
	IMAGE_ZOMBATAR_ACCESSORY_14_ID,
	IMAGE_ZOMBATAR_HATS_1_MASK_ID,
	IMAGE_ZOMBATAR_HAIR_1_MASK_ID,
	IMAGE_ZOMBATAR_HAIR_2_MASK_ID,
	IMAGE_ZOMBATAR_HAIR_11_MASK_ID,
	IMAGE_ZOMBATAR_HAIR_12_MASK_ID,
	IMAGE_ZOMBATAR_HAIR_13_MASK_ID,
	IMAGE_ZOMBATAR_HAIR_14_MASK_ID,
	IMAGE_ZOMBATAR_HAIR_15_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_1_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_4_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_8_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_9_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_10_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_11_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_12_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_14_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_15_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_16_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_18_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_21_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_22_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_23_MASK_ID,
	IMAGE_ZOMBATAR_FACIALHAIR_24_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_1_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_2_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_3_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_4_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_5_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_6_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_7_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_8_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_9_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_10_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_11_MASK_ID,
	IMAGE_ZOMBATAR_EYEWEAR_12_MASK_ID,
	IMAGE_ZOMBATAR_HATS_3_MASK_ID,
	IMAGE_ZOMBATAR_HATS_6_MASK_ID,
	IMAGE_ZOMBATAR_HATS_7_MASK_ID,
	IMAGE_ZOMBATAR_HATS_8_MASK_ID,
	IMAGE_ZOMBATAR_HATS_9_MASK_ID,
	IMAGE_ZOMBATAR_HATS_11_MASK_ID,
	IMAGE_ZOMBATAR_BACKGROUND_BLANK_ID,
	IMAGE_ZOMBATAR_ACCESSORY_15_ID,
	IMAGE_ZOMBATAR_ACCESSORY_16_ID,
	IMAGE_ZOMBATAR_ACCEPT_BUTTON_ID,
	IMAGE_ZOMBATAR_ACCEPT_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_FINISHED_BUTTON_ID,
	IMAGE_ZOMBATAR_FINISHED_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_MAIN_BG_ID,
	IMAGE_ZOMBATAR_BACK_BUTTON_ID,
	IMAGE_ZOMBATAR_BACK_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_NEWZOMBIE_BUTTON_ID,
	IMAGE_ZOMBATAR_NEWZOMBIE_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_TOS_ARROW_ID,
	IMAGE_ZOMBATAR_BEGIN_BUTTON_ID,
	IMAGE_ZOMBATAR_BEGIN_BUTTON_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_TOS_SLIDER_ID,
	IMAGE_ZOMBATAR_TOS_SLIDER_THUMB_ID,
	IMAGE_ZOMBATAR_DISPLAY_WINDOW_ID,
	IMAGE_ZOMBATAR_MAINMENUBACK_HIGHLIGHT_ID,
	IMAGE_ZOMBATAR_VIEW_BUTTON_ID,
	IMAGE_ZOMBATAR_VIEW_BUTTON_HIGHLIGHT_ID,
	RESOURCE_ID_MAX
};

// ---- by-id lookup prototypes ----
Image* GetImageById(ResourceId theId);
_Font* GetFontById(ResourceId theId);
intptr_t GetSoundById(ResourceId theId);
Image*& GetImageRefById(ResourceId theId);
_Font*& GetFontRefById(ResourceId theId);
intptr_t& GetSoundRefById(ResourceId theId);
ResourceId GetIdByImage(Image* theImage);
ResourceId GetIdByFont(_Font* theFont);
ResourceId GetIdBySound(intptr_t theSound);
ResourceId GetIdByVariable(void* theVariable);

// ---- Images (585) ----
extern Image* IMAGE_ALMANAC_CLOSEBUTTON;
extern Image* IMAGE_ALMANAC_CLOSEBUTTONHIGHLIGHT;
extern Image* IMAGE_ALMANAC_GROUNDDAY;
extern Image* IMAGE_ALMANAC_GROUNDICE;
extern Image* IMAGE_ALMANAC_GROUNDNIGHT;
extern Image* IMAGE_ALMANAC_GROUNDNIGHTPOOL;
extern Image* IMAGE_ALMANAC_GROUNDPOOL;
extern Image* IMAGE_ALMANAC_GROUNDROOF;
extern Image* IMAGE_ALMANAC_INDEXBACK;
extern Image* IMAGE_ALMANAC_INDEXBUTTON;
extern Image* IMAGE_ALMANAC_INDEXBUTTONHIGHLIGHT;
extern Image* IMAGE_ALMANAC_PLANTBACK;
extern Image* IMAGE_ALMANAC_PLANTCARD;
extern Image* IMAGE_ALMANAC_ZOMBIEBACK;
extern Image* IMAGE_ALMANAC_ZOMBIEBLANK;
extern Image* IMAGE_ALMANAC_ZOMBIECARD;
extern Image* IMAGE_ALMANAC_ZOMBIEWINDOW;
extern Image* IMAGE_ALMANAC_ZOMBIEWINDOW2;
extern Image* IMAGE_AWARDSCREEN_BACK;
extern Image* IMAGE_BACKGROUND1;
extern Image* IMAGE_BACKGROUND1_GAMEOVER_INTERIOR_OVERLAY;
extern Image* IMAGE_BACKGROUND1_GAMEOVER_MASK;
extern Image* IMAGE_BACKGROUND2;
extern Image* IMAGE_BACKGROUND2_GAMEOVER_INTERIOR_OVERLAY;
extern Image* IMAGE_BACKGROUND2_GAMEOVER_MASK;
extern Image* IMAGE_BACKGROUND3;
extern Image* IMAGE_BACKGROUND3_GAMEOVER_INTERIOR_OVERLAY;
extern Image* IMAGE_BACKGROUND3_GAMEOVER_MASK;
extern Image* IMAGE_BACKGROUND4;
extern Image* IMAGE_BACKGROUND4_GAMEOVER_INTERIOR_OVERLAY;
extern Image* IMAGE_BACKGROUND4_GAMEOVER_MASK;
extern Image* IMAGE_FOG;
extern Image* IMAGE_FOG_SOFTWARE;
extern Image* IMAGE_BACKGROUND5;
extern Image* IMAGE_BACKGROUND5_GAMEOVER_MASK;
extern Image* IMAGE_BACKGROUND6BOSS;
extern Image* IMAGE_BACKGROUND6_GAMEOVER_MASK;
extern Image* IMAGE_BACKGROUND1UNSODDED;
extern Image* IMAGE_SOD1ROW;
extern Image* IMAGE_SOD3ROW;
extern Image* IMAGE_CHALLENGE_BACKGROUND;
extern Image* IMAGE_CHALLENGE_BLANK;
extern Image* IMAGE_CHALLENGE_THUMBNAILS;
extern Image* IMAGE_CHALLENGE_WINDOW;
extern Image* IMAGE_CHALLENGE_WINDOW_HIGHLIGHT;
extern Image* IMAGE_LOCK;
extern Image* IMAGE_LOCK_OPEN;
extern Image* IMAGE_SURVIVAL_THUMBNAILS;
extern Image* IMAGE_CREDITS_PLAYBUTTON;
extern Image* IMAGE_CREDITS_ZOMBIENOTE;
extern Image* IMAGE_REANIM_CREDITS_DISCOLIGHTS;
extern Image* IMAGE_REANIM_CREDITS_FOGMACHINE;
extern Image* IMAGE_REANIM_SUNFLOWER_HEAD_SING1;
extern Image* IMAGE_REANIM_SUNFLOWER_HEAD_SING2;
extern Image* IMAGE_REANIM_SUNFLOWER_HEAD_SING3;
extern Image* IMAGE_REANIM_SUNFLOWER_HEAD_SING4;
extern Image* IMAGE_REANIM_SUNFLOWER_HEAD_SING5;
extern Image* IMAGE_REANIM_SUNFLOWER_HEAD_WINK;
extern Image* IMAGE_BACKGROUND_GREENHOUSE;
extern Image* IMAGE_BACKGROUND_GREENHOUSE_OVERLAY;
extern Image* IMAGE_BACKGROUND_MUSHROOMGARDEN;
extern Image* IMAGE_STORE_AQUARIUMGARDENICON;
extern Image* IMAGE_STORE_BACKGROUND;
extern Image* IMAGE_STORE_BACKGROUNDNIGHT;
extern Image* IMAGE_STORE_CAR;
extern Image* IMAGE_STORE_CARCLOSED;
extern Image* IMAGE_STORE_CARCLOSED_NIGHT;
extern Image* IMAGE_STORE_CAR_NIGHT;
extern Image* IMAGE_STORE_FIRSTAIDWALLNUTICON;
extern Image* IMAGE_STORE_HATCHBACKOPEN;
extern Image* IMAGE_STORE_MAINMENUBUTTON;
extern Image* IMAGE_STORE_MAINMENUBUTTONDOWN;
extern Image* IMAGE_STORE_MAINMENUBUTTONHIGHLIGHT;
extern Image* IMAGE_STORE_MUSHROOMGARDENICON;
extern Image* IMAGE_STORE_NEXTBUTTON;
extern Image* IMAGE_STORE_NEXTBUTTONDISABLED;
extern Image* IMAGE_STORE_NEXTBUTTONHIGHLIGHT;
extern Image* IMAGE_STORE_PACKETUPGRADE;
extern Image* IMAGE_STORE_PREVBUTTON;
extern Image* IMAGE_STORE_PREVBUTTONDISABLED;
extern Image* IMAGE_STORE_PREVBUTTONHIGHLIGHT;
extern Image* IMAGE_STORE_PRICETAG;
extern Image* IMAGE_STORE_PVZICON;
extern Image* IMAGE_STORE_SIGN;
extern Image* IMAGE_STORE_TREEOFWISDOMICON;
extern Image* IMAGE_ZOMBATAR_ACCEPT_BUTTON;
extern Image* IMAGE_ZOMBATAR_ACCEPT_BUTTON_HIGHLIGHT;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_1;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_10;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_11;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_12;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_13;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_14;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_15;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_16;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_2;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_3;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_4;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_5;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_6;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_7;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_8;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_9;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_BG;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_BG_HIGHLIGHT;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_BG_NONE;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_BUTTON;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_BUTTON_HIGHLIGHT;
extern Image* IMAGE_ZOMBATAR_ACCESSORY_BUTTON_OVER;
extern Image* IMAGE_ZOMBATAR_BACKDROPS_BUTTON;
extern Image* IMAGE_ZOMBATAR_BACKDROPS_BUTTON_HIGHLIGHT;
extern Image* IMAGE_ZOMBATAR_BACKDROPS_BUTTON_OVER;
extern Image* IMAGE_ZOMBATAR_BACKGROUND_BLANK;
extern Image* IMAGE_ZOMBATAR_BACKGROUND_CRAZYDAVE;
extern Image* IMAGE_ZOMBATAR_BACKGROUND_MENU;
extern Image* IMAGE_ZOMBATAR_BACKGROUND_MENU_DOS;
extern Image* IMAGE_ZOMBATAR_BACKGROUND_ROOF;
extern Image* IMAGE_ZOMBATAR_BACK_BUTTON;
extern Image* IMAGE_ZOMBATAR_BACK_BUTTON_HIGHLIGHT;
extern Image* IMAGE_ZOMBATAR_BEGIN_BUTTON;
extern Image* IMAGE_ZOMBATAR_BEGIN_BUTTON_HIGHLIGHT;
extern Image* IMAGE_ZOMBATAR_CLOTHES_1;
extern Image* IMAGE_ZOMBATAR_CLOTHES_10;
extern Image* IMAGE_ZOMBATAR_CLOTHES_11;
extern Image* IMAGE_ZOMBATAR_CLOTHES_12;
extern Image* IMAGE_ZOMBATAR_CLOTHES_2;
extern Image* IMAGE_ZOMBATAR_CLOTHES_3;
extern Image* IMAGE_ZOMBATAR_CLOTHES_4;
extern Image* IMAGE_ZOMBATAR_CLOTHES_5;
extern Image* IMAGE_ZOMBATAR_CLOTHES_6;
extern Image* IMAGE_ZOMBATAR_CLOTHES_7;
extern Image* IMAGE_ZOMBATAR_CLOTHES_8;
extern Image* IMAGE_ZOMBATAR_CLOTHES_9;
extern Image* IMAGE_ZOMBATAR_CLOTHES_BUTTON;
extern Image* IMAGE_ZOMBATAR_CLOTHES_BUTTON_HIGHLIGHT;
extern Image* IMAGE_ZOMBATAR_CLOTHES_BUTTON_OVER;
extern Image* IMAGE_ZOMBATAR_COLORPICKER;
extern Image* IMAGE_ZOMBATAR_COLORPICKER_HIGHLIGHT;
extern Image* IMAGE_ZOMBATAR_COLORPICKER_NONE;
extern Image* IMAGE_ZOMBATAR_COLORS_BG;
extern Image* IMAGE_ZOMBATAR_COLORS_BG_SMALL;
extern Image* IMAGE_ZOMBATAR_DISPLAY_WINDOW;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_1;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_10;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_10_MASK;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_11;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_11_MASK;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_12;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_12_MASK;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_13;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_14;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_15;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_16;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_1_MASK;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_2;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_2_MASK;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_3;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_3_MASK;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_4;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_4_MASK;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_5;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_5_MASK;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_6;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_6_MASK;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_7;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_7_MASK;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_8;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_8_MASK;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_9;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_9_MASK;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_BUTTON;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_BUTTON_HIGHLIGHT;
extern Image* IMAGE_ZOMBATAR_EYEWEAR_BUTTON_OVER;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_1;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_10;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_10_MASK;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_11;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_11_MASK;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_12;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_12_MASK;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_13;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_14;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_14_MASK;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_15;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_15_MASK;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_16;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_16_MASK;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_17;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_18;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_18_MASK;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_19;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_1_MASK;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_2;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_20;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_21;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_21_MASK;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_22;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_22_MASK;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_23;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_23_MASK;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_24;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_24_MASK;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_3;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_4;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_4_MASK;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_5;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_6;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_7;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_8;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_8_MASK;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_9;
extern Image* IMAGE_ZOMBATAR_FACIALHAIR_9_MASK;
extern Image* IMAGE_ZOMBATAR_FACIAL_HAIR_BUTTON;
extern Image* IMAGE_ZOMBATAR_FACIAL_HAIR_BUTTON_HIGHLIGHT;
extern Image* IMAGE_ZOMBATAR_FACIAL_HAIR_BUTTON_OVER;
extern Image* IMAGE_ZOMBATAR_FINISHED_BUTTON;
extern Image* IMAGE_ZOMBATAR_FINISHED_BUTTON_HIGHLIGHT;
extern Image* IMAGE_ZOMBATAR_HAIR_1;
extern Image* IMAGE_ZOMBATAR_HAIR_10;
extern Image* IMAGE_ZOMBATAR_HAIR_11;
extern Image* IMAGE_ZOMBATAR_HAIR_11_MASK;
extern Image* IMAGE_ZOMBATAR_HAIR_12;
extern Image* IMAGE_ZOMBATAR_HAIR_12_MASK;
extern Image* IMAGE_ZOMBATAR_HAIR_13;
extern Image* IMAGE_ZOMBATAR_HAIR_13_MASK;
extern Image* IMAGE_ZOMBATAR_HAIR_14;
extern Image* IMAGE_ZOMBATAR_HAIR_14_MASK;
extern Image* IMAGE_ZOMBATAR_HAIR_15;
extern Image* IMAGE_ZOMBATAR_HAIR_15_MASK;
extern Image* IMAGE_ZOMBATAR_HAIR_16;
extern Image* IMAGE_ZOMBATAR_HAIR_1_MASK;
extern Image* IMAGE_ZOMBATAR_HAIR_2;
extern Image* IMAGE_ZOMBATAR_HAIR_2_MASK;
extern Image* IMAGE_ZOMBATAR_HAIR_3;
extern Image* IMAGE_ZOMBATAR_HAIR_4;
extern Image* IMAGE_ZOMBATAR_HAIR_5;
extern Image* IMAGE_ZOMBATAR_HAIR_6;
extern Image* IMAGE_ZOMBATAR_HAIR_7;
extern Image* IMAGE_ZOMBATAR_HAIR_8;
extern Image* IMAGE_ZOMBATAR_HAIR_9;
extern Image* IMAGE_ZOMBATAR_HAIR_BUTTON;
extern Image* IMAGE_ZOMBATAR_HAIR_BUTTON_HIGHLIGHT;
extern Image* IMAGE_ZOMBATAR_HAIR_BUTTON_OVER;
extern Image* IMAGE_ZOMBATAR_HATS_1;
extern Image* IMAGE_ZOMBATAR_HATS_10;
extern Image* IMAGE_ZOMBATAR_HATS_11;
extern Image* IMAGE_ZOMBATAR_HATS_11_MASK;
extern Image* IMAGE_ZOMBATAR_HATS_12;
extern Image* IMAGE_ZOMBATAR_HATS_13;
extern Image* IMAGE_ZOMBATAR_HATS_14;
extern Image* IMAGE_ZOMBATAR_HATS_1_MASK;
extern Image* IMAGE_ZOMBATAR_HATS_2;
extern Image* IMAGE_ZOMBATAR_HATS_3;
extern Image* IMAGE_ZOMBATAR_HATS_3_MASK;
extern Image* IMAGE_ZOMBATAR_HATS_4;
extern Image* IMAGE_ZOMBATAR_HATS_5;
extern Image* IMAGE_ZOMBATAR_HATS_6;
extern Image* IMAGE_ZOMBATAR_HATS_6_MASK;
extern Image* IMAGE_ZOMBATAR_HATS_7;
extern Image* IMAGE_ZOMBATAR_HATS_7_MASK;
extern Image* IMAGE_ZOMBATAR_HATS_8;
extern Image* IMAGE_ZOMBATAR_HATS_8_MASK;
extern Image* IMAGE_ZOMBATAR_HATS_9;
extern Image* IMAGE_ZOMBATAR_HATS_9_MASK;
extern Image* IMAGE_ZOMBATAR_HATS_BUTTON;
extern Image* IMAGE_ZOMBATAR_HATS_BUTTON_HIGHLIGHT;
extern Image* IMAGE_ZOMBATAR_HATS_BUTTON_OVER;
extern Image* IMAGE_ZOMBATAR_LOGO;
extern Image* IMAGE_ZOMBATAR_MAINMENUBACK_HIGHLIGHT;
extern Image* IMAGE_ZOMBATAR_MAIN_BG;
extern Image* IMAGE_ZOMBATAR_NEWZOMBIE_BUTTON;
extern Image* IMAGE_ZOMBATAR_NEWZOMBIE_BUTTON_HIGHLIGHT;
extern Image* IMAGE_ZOMBATAR_NEXT_BUTTON;
extern Image* IMAGE_ZOMBATAR_NEXT_BUTTON_HIGHLIGHT;
extern Image* IMAGE_ZOMBATAR_PREV_BUTTON;
extern Image* IMAGE_ZOMBATAR_PREV_BUTTON_HIGHLIGHT;
extern Image* IMAGE_ZOMBATAR_SKIN_BUTTON;
extern Image* IMAGE_ZOMBATAR_SKIN_BUTTON_HIGHLIGHT;
extern Image* IMAGE_ZOMBATAR_TIDBITS_1;
extern Image* IMAGE_ZOMBATAR_TIDBITS_10;
extern Image* IMAGE_ZOMBATAR_TIDBITS_11;
extern Image* IMAGE_ZOMBATAR_TIDBITS_12;
extern Image* IMAGE_ZOMBATAR_TIDBITS_13;
extern Image* IMAGE_ZOMBATAR_TIDBITS_14;
extern Image* IMAGE_ZOMBATAR_TIDBITS_2;
extern Image* IMAGE_ZOMBATAR_TIDBITS_3;
extern Image* IMAGE_ZOMBATAR_TIDBITS_4;
extern Image* IMAGE_ZOMBATAR_TIDBITS_5;
extern Image* IMAGE_ZOMBATAR_TIDBITS_6;
extern Image* IMAGE_ZOMBATAR_TIDBITS_7;
extern Image* IMAGE_ZOMBATAR_TIDBITS_8;
extern Image* IMAGE_ZOMBATAR_TIDBITS_9;
extern Image* IMAGE_ZOMBATAR_TIDBITS_BUTTON;
extern Image* IMAGE_ZOMBATAR_TIDBITS_BUTTON_HIGHLIGHT;
extern Image* IMAGE_ZOMBATAR_TIDBITS_BUTTON_OVER;
extern Image* IMAGE_ZOMBATAR_TOS_ARROW;
extern Image* IMAGE_ZOMBATAR_TOS_SLIDER;
extern Image* IMAGE_ZOMBATAR_TOS_SLIDER_THUMB;
extern Image* IMAGE_ZOMBATAR_TRIPTYCH;
extern Image* IMAGE_ZOMBATAR_VIEW_BUTTON;
extern Image* IMAGE_ZOMBATAR_VIEW_BUTTON_HIGHLIGHT;
extern Image* IMAGE_ZOMBATAR_WIDGET_BG;
extern Image* IMAGE_ZOMBATAR_WIDGET_INNER_BG;
extern Image* IMAGE_ZOMBATAR_ZOMBIE_BLANK;
extern Image* IMAGE_ZOMBATAR_ZOMBIE_BLANK_SKIN;
extern Image* IMAGE_ZOMBIE_FINAL_NOTE;
extern Image* IMAGE_ZOMBIE_NOTE;
extern Image* IMAGE_ZOMBIE_NOTE1;
extern Image* IMAGE_ZOMBIE_NOTE2;
extern Image* IMAGE_ZOMBIE_NOTE3;
extern Image* IMAGE_ZOMBIE_NOTE4;
extern Image* IMAGE_ZOMBIE_NOTE_HELP;
extern Image* IMAGE_AQUARIUM1;
extern Image* IMAGE_WAVECENTER;
extern Image* IMAGE_WAVESIDE;
extern Image* IMAGE_BLANK;
extern Image* IMAGE_PARTNER_LOGO;
extern Image* IMAGE_POPCAP_LOGO;
extern Image* IMAGE_LOADBAR_DIRT;
extern Image* IMAGE_LOADBAR_GRASS;
extern Image* IMAGE_PVZ_LOGO;
extern Image* IMAGE_REANIM_SODROLLCAP;
extern Image* IMAGE_TITLESCREEN;
extern Image* IMAGE_ACHEESEMENTS_BACK_HIGHLIGHT;
extern Image* IMAGE_ACHEESEMENTS_BEJEWELED;
extern Image* IMAGE_ACHEESEMENTS_BOOKWORM;
extern Image* IMAGE_ACHEESEMENTS_CHINA;
extern Image* IMAGE_ACHEESEMENTS_CHUZZLE;
extern Image* IMAGE_ACHEESEMENTS_HOLE_TILE;
extern Image* IMAGE_ACHEESEMENTS_ICONS;
extern Image* IMAGE_ACHEESEMENTS_MORE_BUTTON;
extern Image* IMAGE_ACHEESEMENTS_MORE_BUTTON_HIGHLIGHT;
extern Image* IMAGE_ACHEESEMENTS_MORE_ROCK;
extern Image* IMAGE_ACHEESEMENTS_PEGGLE;
extern Image* IMAGE_ACHEESEMENTS_PIPE;
extern Image* IMAGE_ACHEESEMENTS_TOP_BUTTON;
extern Image* IMAGE_ACHEESEMENTS_TOP_BUTTON_HIGHLIGHT;
extern Image* IMAGE_ACHEESEMENTS_ZUMA;
extern Image* IMAGE_ALMANAC;
extern Image* IMAGE_ALMANAC_IMITATER;
extern Image* IMAGE_AWARDPICKUPGLOW;
extern Image* IMAGE_BEGHOULED_TWIST_OVERLAY;
extern Image* IMAGE_BRAIN;
extern Image* IMAGE_BUG_SPRAY;
extern Image* IMAGE_BUNGEECORD;
extern Image* IMAGE_BUNGEETARGET;
extern Image* IMAGE_BUTTON_DOWN_LEFT;
extern Image* IMAGE_BUTTON_DOWN_MIDDLE;
extern Image* IMAGE_BUTTON_DOWN_RIGHT;
extern Image* IMAGE_BUTTON_LEFT;
extern Image* IMAGE_BUTTON_MIDDLE;
extern Image* IMAGE_BUTTON_RIGHT;
extern Image* IMAGE_CARKEYS;
extern Image* IMAGE_CHOCOLATE;
extern Image* IMAGE_COBCANNON_POPCORN;
extern Image* IMAGE_COBCANNON_TARGET;
extern Image* IMAGE_COINBANK;
extern Image* IMAGE_CONVEYORBELT;
extern Image* IMAGE_CONVEYORBELT_BACKDROP;
extern Image* IMAGE_CRATER;
extern Image* IMAGE_CRATER_FADING;
extern Image* IMAGE_CRATER_ROOF_CENTER;
extern Image* IMAGE_CRATER_ROOF_LEFT;
extern Image* IMAGE_CRATER_WATER_DAY;
extern Image* IMAGE_CRATER_WATER_NIGHT;
extern Image* IMAGE_DIALOG_BIGBOTTOMLEFT;
extern Image* IMAGE_DIALOG_BIGBOTTOMMIDDLE;
extern Image* IMAGE_DIALOG_BIGBOTTOMRIGHT;
extern Image* IMAGE_DIALOG_BOTTOMLEFT;
extern Image* IMAGE_DIALOG_BOTTOMMIDDLE;
extern Image* IMAGE_DIALOG_BOTTOMRIGHT;
extern Image* IMAGE_DIALOG_CENTERLEFT;
extern Image* IMAGE_DIALOG_CENTERMIDDLE;
extern Image* IMAGE_DIALOG_CENTERRIGHT;
extern Image* IMAGE_DIALOG_HEADER;
extern Image* IMAGE_DIALOG_TOPLEFT;
extern Image* IMAGE_DIALOG_TOPMIDDLE;
extern Image* IMAGE_DIALOG_TOPRIGHT;
extern Image* IMAGE_DIRTBIG;
extern Image* IMAGE_DIRTSMALL;
extern Image* IMAGE_DOOMSHROOM_EXPLOSION_BASE;
extern Image* IMAGE_DUST_PUFFS;
extern Image* IMAGE_EDITBOX;
extern Image* IMAGE_FERTILIZER;
extern Image* IMAGE_FLAGMETER;
extern Image* IMAGE_FLAGMETERLEVELPROGRESS;
extern Image* IMAGE_FLAGMETERPARTS;
extern Image* IMAGE_ICE;
extern Image* IMAGE_ICETRAP;
extern Image* IMAGE_ICETRAP2;
extern Image* IMAGE_ICETRAP_PARTICLES;
extern Image* IMAGE_ICE_CAP;
extern Image* IMAGE_ICE_SPARKLES;
extern Image* IMAGE_ICON_POOLCLEANER;
extern Image* IMAGE_ICON_RAKE;
extern Image* IMAGE_ICON_ROOFCLEANER;
extern Image* IMAGE_IMITATERCLOUDS;
extern Image* IMAGE_IMITATERPUFFS;
extern Image* IMAGE_IMITATERSEED;
extern Image* IMAGE_IMITATERSEEDDISABLED;
extern Image* IMAGE_MELONPULT_PARTICLES;
extern Image* IMAGE_MINIGAME_TROPHY;
extern Image* IMAGE_MONEYBAG;
extern Image* IMAGE_MONEYBAG_HI_RES;
extern Image* IMAGE_NIGHT_GRAVE_GRAPHIC;
extern Image* IMAGE_OPTIONS_BACKTOGAMEBUTTON0;
extern Image* IMAGE_OPTIONS_BACKTOGAMEBUTTON2;
extern Image* IMAGE_OPTIONS_CHECKBOX0;
extern Image* IMAGE_OPTIONS_CHECKBOX1;
extern Image* IMAGE_OPTIONS_MENUBACK;
extern Image* IMAGE_OPTIONS_SLIDERKNOB2;
extern Image* IMAGE_OPTIONS_SLIDERSLOT;
extern Image* IMAGE_PACKET_PLANTS;
extern Image* IMAGE_PEA_PARTICLES;
extern Image* IMAGE_PEA_SHADOWS;
extern Image* IMAGE_PEA_SPLATS;
extern Image* IMAGE_PHONOGRAPH;
extern Image* IMAGE_PINATA;
extern Image* IMAGE_PLANTSHADOW;
extern Image* IMAGE_PLANTSHADOW2;
extern Image* IMAGE_PLANTSPEECHBUBBLE;
extern Image* IMAGE_POOL;
extern Image* IMAGE_POOLSPARKLY;
extern Image* IMAGE_POOL_BASE;
extern Image* IMAGE_POOL_BASE_NIGHT;
extern Image* IMAGE_POOL_CAUSTIC_EFFECT;
extern Image* IMAGE_POOL_NIGHT;
extern Image* IMAGE_POOL_SHADING;
extern Image* IMAGE_POOL_SHADING_NIGHT;
extern Image* IMAGE_POTATOMINE_PARTICLES;
extern Image* IMAGE_PRESENT;
extern Image* IMAGE_PRESENTOPEN;
extern Image* IMAGE_PROJECTILECACTUS;
extern Image* IMAGE_PROJECTILEPEA;
extern Image* IMAGE_PROJECTILESNOWPEA;
extern Image* IMAGE_PROJECTILE_STAR;
extern Image* IMAGE_PUFFSHROOM_PUFF1;
extern Image* IMAGE_QUICKPLAY_BACK_BUTTON;
extern Image* IMAGE_QUICKPLAY_BACK_BUTTON_HIGHLIGHT;
extern Image* IMAGE_QUICKPLAY_MINIGAMES_BUTTON;
extern Image* IMAGE_QUICKPLAY_MINIGAMES_BUTTON_HIGHLIGHT;
extern Image* IMAGE_QUICKPLAY_MINIGAMES_CLOUD;
extern Image* IMAGE_QUICKPLAY_PUZZLES_BUTTON;
extern Image* IMAGE_QUICKPLAY_PUZZLES_BUTTON_HIGHLIGHT;
extern Image* IMAGE_QUICKPLAY_PUZZLES_CLOUD;
extern Image* IMAGE_QUICKPLAY_SURVIVAL_BUTTON;
extern Image* IMAGE_QUICKPLAY_SURVIVAL_BUTTON_HIGHLIGHT;
extern Image* IMAGE_QUICKPLAY_SURVIVAL_CLOUD;
extern Image* IMAGE_RAIN;
extern Image* IMAGE_REANIM_CABBAGEPULT_CABBAGE;
extern Image* IMAGE_REANIM_COBCANNON_COB;
extern Image* IMAGE_REANIM_COINGLOW;
extern Image* IMAGE_REANIM_COIN_GOLD_DOLLAR;
extern Image* IMAGE_REANIM_COIN_SILVER_DOLLAR;
extern Image* IMAGE_REANIM_CORNPULT_BUTTER;
extern Image* IMAGE_REANIM_CORNPULT_BUTTER_SPLAT;
extern Image* IMAGE_REANIM_CORNPULT_KERNAL;
extern Image* IMAGE_REANIM_CRAZYDAVE_MOUTH1;
extern Image* IMAGE_REANIM_CRAZYDAVE_MOUTH4;
extern Image* IMAGE_REANIM_CRAZYDAVE_MOUTH5;
extern Image* IMAGE_REANIM_CRAZYDAVE_MOUTH6;
extern Image* IMAGE_REANIM_DIAMOND;
extern Image* IMAGE_REANIM_GARLIC_BODY2;
extern Image* IMAGE_REANIM_GARLIC_BODY3;
extern Image* IMAGE_REANIM_MELONPULT_MELON;
extern Image* IMAGE_REANIM_POT_TOP_DARK;
extern Image* IMAGE_REANIM_PUMPKIN_DAMAGE1;
extern Image* IMAGE_REANIM_PUMPKIN_DAMAGE3;
extern Image* IMAGE_REANIM_SELECTORSCREEN_ADVENTURE_BUTTON;
extern Image* IMAGE_REANIM_SELECTORSCREEN_ADVENTURE_HIGHLIGHT;
extern Image* IMAGE_REANIM_SELECTORSCREEN_ALMANAC_SHADOW;
extern Image* IMAGE_REANIM_SELECTORSCREEN_BG;
extern Image* IMAGE_REANIM_SELECTORSCREEN_CHALLENGES_BUTTON;
extern Image* IMAGE_REANIM_SELECTORSCREEN_CHALLENGES_HIGHLIGHT;
extern Image* IMAGE_REANIM_SELECTORSCREEN_KEY_SHADOW;
extern Image* IMAGE_REANIM_SELECTORSCREEN_STARTADVENTURE_BUTTON;
extern Image* IMAGE_REANIM_SELECTORSCREEN_STARTADVENTURE_HIGHLIGHT;
extern Image* IMAGE_REANIM_SELECTORSCREEN_SURVIVAL_BUTTON;
extern Image* IMAGE_REANIM_SELECTORSCREEN_SURVIVAL_HIGHLIGHT;
extern Image* IMAGE_REANIM_SELECTORSCREEN_VASEBREAKER_BUTTON;
extern Image* IMAGE_REANIM_SELECTORSCREEN_VASEBREAKER_HIGHLIGHT;
extern Image* IMAGE_REANIM_SELECTORSCREEN_WOODSIGN2_PRESS;
extern Image* IMAGE_REANIM_SELECTORSCREEN_WOODSIGN3_PRESS;
extern Image* IMAGE_REANIM_STINKY_TURN3;
extern Image* IMAGE_REANIM_TALLNUT_CRACKED1;
extern Image* IMAGE_REANIM_TALLNUT_CRACKED2;
extern Image* IMAGE_REANIM_TREE_BG;
extern Image* IMAGE_REANIM_WALLNUT_BODY;
extern Image* IMAGE_REANIM_WALLNUT_CRACKED1;
extern Image* IMAGE_REANIM_WALLNUT_CRACKED2;
extern Image* IMAGE_REANIM_WINTERMELON_PROJECTILE;
extern Image* IMAGE_REANIM_ZENGARDEN_BUGSPRAY_BOTTLE;
extern Image* IMAGE_REANIM_ZOMBIE_BACKUP_INNERARM_HAND;
extern Image* IMAGE_REANIM_ZOMBIE_BACKUP_OUTERARM_UPPER2;
extern Image* IMAGE_REANIM_ZOMBIE_BALLOON_OUTERARM_UPPER2;
extern Image* IMAGE_REANIM_ZOMBIE_BOBSLED_OUTERARM_HAND;
extern Image* IMAGE_REANIM_ZOMBIE_BOBSLED_OUTERARM_UPPER2;
extern Image* IMAGE_REANIM_ZOMBIE_BOSS_EYEGLOW_BLUE;
extern Image* IMAGE_REANIM_ZOMBIE_BOSS_FOOT_DAMAGE1;
extern Image* IMAGE_REANIM_ZOMBIE_BOSS_FOOT_DAMAGE2;
extern Image* IMAGE_REANIM_ZOMBIE_BOSS_HEAD_DAMAGE1;
extern Image* IMAGE_REANIM_ZOMBIE_BOSS_HEAD_DAMAGE2;
extern Image* IMAGE_REANIM_ZOMBIE_BOSS_ICEBALL;
extern Image* IMAGE_REANIM_ZOMBIE_BOSS_JAW_DAMAGE1;
extern Image* IMAGE_REANIM_ZOMBIE_BOSS_JAW_DAMAGE2;
extern Image* IMAGE_REANIM_ZOMBIE_BOSS_MOUTHGLOW_BLUE;
extern Image* IMAGE_REANIM_ZOMBIE_BOSS_OUTERARM_HAND_DAMAGE1;
extern Image* IMAGE_REANIM_ZOMBIE_BOSS_OUTERARM_HAND_DAMAGE2;
extern Image* IMAGE_REANIM_ZOMBIE_BOSS_OUTERARM_THUMB_DAMAGE1;
extern Image* IMAGE_REANIM_ZOMBIE_BOSS_OUTERARM_THUMB_DAMAGE2;
extern Image* IMAGE_REANIM_ZOMBIE_BUCKET1;
extern Image* IMAGE_REANIM_ZOMBIE_BUCKET2;
extern Image* IMAGE_REANIM_ZOMBIE_BUCKET3;
extern Image* IMAGE_REANIM_ZOMBIE_BUNGI_HEAD_SCARED;
extern Image* IMAGE_REANIM_ZOMBIE_CATAPULT_BASKETBALL;
extern Image* IMAGE_REANIM_ZOMBIE_CATAPULT_POLE;
extern Image* IMAGE_REANIM_ZOMBIE_CATAPULT_POLE_DAMAGE;
extern Image* IMAGE_REANIM_ZOMBIE_CATAPULT_POLE_DAMAGE_WITHBALL;
extern Image* IMAGE_REANIM_ZOMBIE_CATAPULT_POLE_WITHBALL;
extern Image* IMAGE_REANIM_ZOMBIE_CATAPULT_SIDING_DAMAGE;
extern Image* IMAGE_REANIM_ZOMBIE_CONE1;
extern Image* IMAGE_REANIM_ZOMBIE_CONE2;
extern Image* IMAGE_REANIM_ZOMBIE_CONE3;
extern Image* IMAGE_REANIM_ZOMBIE_DIGGER_HARDHAT;
extern Image* IMAGE_REANIM_ZOMBIE_DIGGER_HARDHAT2;
extern Image* IMAGE_REANIM_ZOMBIE_DIGGER_HARDHAT3;
extern Image* IMAGE_REANIM_ZOMBIE_DIGGER_OUTERARM_UPPER2;
extern Image* IMAGE_REANIM_ZOMBIE_DIGGER_PICKAXE;
extern Image* IMAGE_REANIM_ZOMBIE_DISCO_OUTERARM_HAND;
extern Image* IMAGE_REANIM_ZOMBIE_DISCO_OUTERARM_UPPER2;
extern Image* IMAGE_REANIM_ZOMBIE_DOLPHINRIDER_OUTERARM_UPPER2;
extern Image* IMAGE_REANIM_ZOMBIE_FLAG1;
extern Image* IMAGE_REANIM_ZOMBIE_FLAG3;
extern Image* IMAGE_REANIM_ZOMBIE_FOOTBALL_HELMET;
extern Image* IMAGE_REANIM_ZOMBIE_FOOTBALL_HELMET2;
extern Image* IMAGE_REANIM_ZOMBIE_FOOTBALL_HELMET3;
extern Image* IMAGE_REANIM_ZOMBIE_FOOTBALL_LEFTARM_HAND;
extern Image* IMAGE_REANIM_ZOMBIE_FOOTBALL_LEFTARM_UPPER2;
extern Image* IMAGE_REANIM_ZOMBIE_PAPER_LEFTARM_UPPER2;
extern Image* IMAGE_REANIM_ZOMBIE_PAPER_LEFTARM_LOWER;
extern Image* IMAGE_REANIM_ZOMBIE_PAPER_PAPER2;
extern Image* IMAGE_REANIM_ZOMBIE_PAPER_PAPER3;
extern Image* IMAGE_REANIM_ZOMBIE_PAPER_MADHEAD;
extern Image* IMAGE_REANIM_ZOMBIE_ZAMBONI_1_DAMAGE1;
extern Image* IMAGE_REANIM_ZOMBIE_ZAMBONI_1_DAMAGE2;
extern Image* IMAGE_REANIM_ZOMBIE_ZAMBONI_2_DAMAGE1;
extern Image* IMAGE_REANIM_ZOMBIE_ZAMBONI_2_DAMAGE2;
extern Image* IMAGE_REANIM_ZOMBIE_ZAMBONI_WHEEL_FLAT;
extern Image* IMAGE_REANIM_ZOMBIE_POLEVAULTER_OUTERARM_UPPER2;
extern Image* IMAGE_REANIM_ZOMBIE_OUTERARM_HAND;
extern Image* IMAGE_REANIM_ZOMBIE_IMP_ARM1_BONE;
extern Image* IMAGE_REANIM_ZOMBIE_IMP_ARM2;
extern Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_BODY1_2;
extern Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_BODY1_3;
extern Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_DUCKXING;
extern Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_ZOMBIE;
extern Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_FOOT2;
extern Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_HEAD2;
extern Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_OUTERARM_LOWER2;
extern Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_HEAD2_REDEYE;
extern Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_HEAD_REDEYE;
extern Image* IMAGE_REANIM_ZOMBIE_POGO_OUTERARM_UPPER2;
extern Image* IMAGE_REANIM_ZOMBIE_POGO_STICKDAMAGE1;
extern Image* IMAGE_REANIM_ZOMBIE_POGO_STICKDAMAGE2;
extern Image* IMAGE_REANIM_ZOMBIE_POGO_STICK2DAMAGE1;
extern Image* IMAGE_REANIM_ZOMBIE_POGO_STICK2DAMAGE2;
extern Image* IMAGE_REANIM_ZOMBIE_POGO_STICKHANDS2;
extern Image* IMAGE_REANIM_ZOMBIE_JACKBOX_BOX;
extern Image* IMAGE_REANIM_ZOMBIE_JACKBOX_OUTERARM_LOWER2;
extern Image* IMAGE_REANIM_ZOMBIE_SNORKLE_OUTERARM_UPPER2;
extern Image* IMAGE_REANIM_ZOMBIE_LADDER_1;
extern Image* IMAGE_REANIM_ZOMBIE_LADDER_1_DAMAGE1;
extern Image* IMAGE_REANIM_ZOMBIE_LADDER_1_DAMAGE2;
extern Image* IMAGE_REANIM_ZOMBIE_LADDER_5;
extern Image* IMAGE_REANIM_ZOMBIE_LADDER_OUTERARM_UPPER2;
extern Image* IMAGE_REANIM_ZOMBIE_HEAD_GROSSOUT;
extern Image* IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES1;
extern Image* IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES2;
extern Image* IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES3;
extern Image* IMAGE_REANIM_ZOMBIE_HEAD_SUNGLASSES4;
extern Image* IMAGE_REANIM_ZOMBIE_YETI_OUTERARM_UPPER2;
extern Image* IMAGE_REANIM_ZOMBIE_YETI_OUTERARM_HAND;
extern Image* IMAGE_REANIM_ZOMBIE_SNORKLE_HEAD;
extern Image* IMAGE_REANIM_ZOMBIE_MUSTACHE2;
extern Image* IMAGE_REANIM_ZOMBIE_MUSTACHE3;

// ---- Fonts (21) ----
extern _Font* FONT_BRIANNETOD32;
extern _Font* FONT_BRIANNETOD32BLACK;
extern _Font* FONT_BRIANNETOD16;
extern _Font* FONT_BRIANNETOD12;
extern _Font* FONT_CONTINUUMBOLD14;
extern _Font* FONT_CONTINUUMBOLD14OUTLINE;
extern _Font* FONT_DWARVENTODCRAFT12;
extern _Font* FONT_DWARVENTODCRAFT15;
extern _Font* FONT_DWARVENTODCRAFT18;
extern _Font* FONT_DWARVENTODCRAFT18BRIGHTGREENINSET;
extern _Font* FONT_DWARVENTODCRAFT18GREENINSET;
extern _Font* FONT_DWARVENTODCRAFT18YELLOW;
extern _Font* FONT_DWARVENTODCRAFT24;
extern _Font* FONT_DWARVENTODCRAFT36BRIGHTGREENINSET;
extern _Font* FONT_DWARVENTODCRAFT36GREENINSET;
extern _Font* FONT_HOUSEOFTERROR16;
extern _Font* FONT_HOUSEOFTERROR20;
extern _Font* FONT_HOUSEOFTERROR28;
extern Image* FONT_IMAGE_HOUSEOFTERROR28;
extern _Font* FONT_PICO129;
extern _Font* FONT_TINYBOLD;

// ---- Sounds (ids) (168) ----
extern intptr_t SOUND_BUTTONCLICK;
extern intptr_t SOUND_LOADINGBAR_FLOWER;
extern intptr_t SOUND_LOADINGBAR_ZOMBIE;
extern intptr_t SOUND_ACHIEVEMENT;
extern intptr_t SOUND_AWOOGA;
extern intptr_t SOUND_BLEEP;
extern intptr_t SOUND_BUZZER;
extern intptr_t SOUND_CHOMP;
extern intptr_t SOUND_CHOMP2;
extern intptr_t SOUND_CHOMPSOFT;
extern intptr_t SOUND_EVILLAUGH;
extern intptr_t SOUND_FLOOP;
extern intptr_t SOUND_FROZEN;
extern intptr_t SOUND_GULP;
extern intptr_t SOUND_GROAN;
extern intptr_t SOUND_GROAN2;
extern intptr_t SOUND_GROAN3;
extern intptr_t SOUND_GROAN4;
extern intptr_t SOUND_GROAN5;
extern intptr_t SOUND_GROAN6;
extern intptr_t SOUND_LOSEMUSIC;
extern intptr_t SOUND_MINDCONTROLLED;
extern intptr_t SOUND_PAUSE;
extern intptr_t SOUND_PLANT;
extern intptr_t SOUND_PLANT2;
extern intptr_t SOUND_POINTS;
extern intptr_t SOUND_SEEDLIFT;
extern intptr_t SOUND_SIREN;
extern intptr_t SOUND_SLURP;
extern intptr_t SOUND_SPLAT;
extern intptr_t SOUND_SPLAT2;
extern intptr_t SOUND_SPLAT3;
extern intptr_t SOUND_SUKHBIR;
extern intptr_t SOUND_SUKHBIR2;
extern intptr_t SOUND_SUKHBIR3;
extern intptr_t SOUND_SUKHBIR4;
extern intptr_t SOUND_SUKHBIR5;
extern intptr_t SOUND_SUKHBIR6;
extern intptr_t SOUND_TAP;
extern intptr_t SOUND_TAP2;
extern intptr_t SOUND_THROW;
extern intptr_t SOUND_THROW2;
extern intptr_t SOUND_BLOVER;
extern intptr_t SOUND_WINMUSIC;
extern intptr_t SOUND_LAWNMOWER;
extern intptr_t SOUND_BOING;
extern intptr_t SOUND_JACKINTHEBOX;
extern intptr_t SOUND_DIAMOND;
extern intptr_t SOUND_DOLPHIN_APPEARS;
extern intptr_t SOUND_DOLPHIN_BEFORE_JUMPING;
extern intptr_t SOUND_POTATO_MINE;
extern intptr_t SOUND_ZAMBONI;
extern intptr_t SOUND_BALLOON_POP;
extern intptr_t SOUND_THUNDER;
extern intptr_t SOUND_ZOMBIESPLASH;
extern intptr_t SOUND_BOWLING;
extern intptr_t SOUND_BOWLINGIMPACT;
extern intptr_t SOUND_BOWLINGIMPACT2;
extern intptr_t SOUND_GRAVEBUSTERCHOMP;
extern intptr_t SOUND_GRAVEBUTTON;
extern intptr_t SOUND_LIMBS_POP;
extern intptr_t SOUND_PLANTERN;
extern intptr_t SOUND_POGO_ZOMBIE;
extern intptr_t SOUND_SNOW_PEA_SPARKLES;
extern intptr_t SOUND_PLANT_WATER;
extern intptr_t SOUND_ZOMBIE_ENTERING_WATER;
extern intptr_t SOUND_ZOMBIE_FALLING_1;
extern intptr_t SOUND_ZOMBIE_FALLING_2;
extern intptr_t SOUND_PUFF;
extern intptr_t SOUND_FUME;
extern intptr_t SOUND_HUGE_WAVE;
extern intptr_t SOUND_SLOT_MACHINE;
extern intptr_t SOUND_COIN;
extern intptr_t SOUND_ROLL_IN;
extern intptr_t SOUND_DIGGER_ZOMBIE;
extern intptr_t SOUND_HATCHBACK_CLOSE;
extern intptr_t SOUND_HATCHBACK_OPEN;
extern intptr_t SOUND_KERNELPULT;
extern intptr_t SOUND_KERNELPULT2;
extern intptr_t SOUND_ZOMBAQUARIUM_DIE;
extern intptr_t SOUND_BUNGEE_SCREAM;
extern intptr_t SOUND_BUNGEE_SCREAM2;
extern intptr_t SOUND_BUNGEE_SCREAM3;
extern intptr_t SOUND_BUTTER;
extern intptr_t SOUND_JACK_SURPRISE;
extern intptr_t SOUND_JACK_SURPRISE2;
extern intptr_t SOUND_NEWSPAPER_RARRGH;
extern intptr_t SOUND_NEWSPAPER_RARRGH2;
extern intptr_t SOUND_NEWSPAPER_RIP;
extern intptr_t SOUND_SQUASH_HMM;
extern intptr_t SOUND_SQUASH_HMM2;
extern intptr_t SOUND_VASE_BREAKING;
extern intptr_t SOUND_POOL_CLEANER;
extern intptr_t SOUND_MAGNETSHROOM;
extern intptr_t SOUND_LADDER_ZOMBIE;
extern intptr_t SOUND_GARGANTUAR_THUMP;
extern intptr_t SOUND_BASKETBALL;
extern intptr_t SOUND_FIREPEA;
extern intptr_t SOUND_IGNITE;
extern intptr_t SOUND_IGNITE2;
extern intptr_t SOUND_READYSETPLANT;
extern intptr_t SOUND_DOOMSHROOM;
extern intptr_t SOUND_EXPLOSION;
extern intptr_t SOUND_FINALWAVE;
extern intptr_t SOUND_REVERSE_EXPLOSION;
extern intptr_t SOUND_RVTHROW;
extern intptr_t SOUND_SHIELDHIT;
extern intptr_t SOUND_SHIELDHIT2;
extern intptr_t SOUND_BOSSEXPLOSION;
extern intptr_t SOUND_CHERRYBOMB;
extern intptr_t SOUND_BONK;
extern intptr_t SOUND_SWING;
extern intptr_t SOUND_RAIN;
extern intptr_t SOUND_LIGHTFILL;
extern intptr_t SOUND_PLASTICHIT;
extern intptr_t SOUND_PLASTICHIT2;
extern intptr_t SOUND_JALAPENO;
extern intptr_t SOUND_BALLOONINFLATE;
extern intptr_t SOUND_BIGCHOMP;
extern intptr_t SOUND_MELONIMPACT;
extern intptr_t SOUND_MELONIMPACT2;
extern intptr_t SOUND_PLANTGROW;
extern intptr_t SOUND_SHOOP;
extern intptr_t SOUND_TAPGLASS;
extern intptr_t SOUND_JUICY;
extern intptr_t SOUND_COFFEE;
extern intptr_t SOUND_WAKEUP;
extern intptr_t SOUND_LOWGROAN;
extern intptr_t SOUND_LOWGROAN2;
extern intptr_t SOUND_PRIZE;
extern intptr_t SOUND_YUCK;
extern intptr_t SOUND_YUCK2;
extern intptr_t SOUND_GRASSSTEP;
extern intptr_t SOUND_SHOVEL;
extern intptr_t SOUND_COBLAUNCH;
extern intptr_t SOUND_WATERING;
extern intptr_t SOUND_POLEVAULT;
extern intptr_t SOUND_GRAVESTONE_RUMBLE;
extern intptr_t SOUND_DIRT_RISE;
extern intptr_t SOUND_FERTILIZER;
extern intptr_t SOUND_PORTAL;
extern intptr_t SOUND_BUGSPRAY;
extern intptr_t SOUND_SCREAM;
extern intptr_t SOUND_PAPER;
extern intptr_t SOUND_MONEYFALLS;
extern intptr_t SOUND_IMP;
extern intptr_t SOUND_IMP2;
extern intptr_t SOUND_HYDRAULIC_SHORT;
extern intptr_t SOUND_HYDRAULIC;
extern intptr_t SOUND_GARGANTUDEATH;
extern intptr_t SOUND_CERAMIC;
extern intptr_t SOUND_BOSSBOULDERATTACK;
extern intptr_t SOUND_CHIME;
extern intptr_t SOUND_CRAZYDAVESHORT1;
extern intptr_t SOUND_CRAZYDAVESHORT2;
extern intptr_t SOUND_CRAZYDAVESHORT3;
extern intptr_t SOUND_CRAZYDAVELONG1;
extern intptr_t SOUND_CRAZYDAVELONG2;
extern intptr_t SOUND_CRAZYDAVELONG3;
extern intptr_t SOUND_CRAZYDAVEEXTRALONG1;
extern intptr_t SOUND_CRAZYDAVEEXTRALONG2;
extern intptr_t SOUND_CRAZYDAVEEXTRALONG3;
extern intptr_t SOUND_CRAZYDAVECRAZY;
extern intptr_t SOUND_PHONOGRAPH;
extern intptr_t SOUND_DANCER;
extern intptr_t SOUND_FINALFANFARE;
extern intptr_t SOUND_CRAZYDAVESCREAM;
extern intptr_t SOUND_CRAZYDAVESCREAM2;

// ---- Extractor prototypes (30) ----
bool ExtractDelayLoad_AlmanacResources(ResourceManager* theManager);
bool ExtractDelayLoad_AwardScreenResources(ResourceManager* theManager);
bool ExtractDelayLoad_Background1Resources(ResourceManager* theManager);
bool ExtractDelayLoad_Background2Resources(ResourceManager* theManager);
bool ExtractDelayLoad_Background3Resources(ResourceManager* theManager);
bool ExtractDelayLoad_Background4Resources(ResourceManager* theManager);
bool ExtractDelayLoad_Background5Resources(ResourceManager* theManager);
bool ExtractDelayLoad_Background6Resources(ResourceManager* theManager);
bool ExtractDelayLoad_BackgroundUnsoddedResources(ResourceManager* theManager);
bool ExtractDelayLoad_ChallengeScreenResources(ResourceManager* theManager);
bool ExtractDelayLoad_CreditsResources(ResourceManager* theManager);
bool ExtractDelayLoad_GreenHouseGardenResources(ResourceManager* theManager);
bool ExtractDelayLoad_GreenHouseOverlayResources(ResourceManager* theManager);
bool ExtractDelayLoad_MushroomGardenResources(ResourceManager* theManager);
bool ExtractDelayLoad_StoreResources(ResourceManager* theManager);
bool ExtractDelayLoad_ZombatarResources(ResourceManager* theManager);
bool ExtractDelayLoad_ZombieFinalNoteResources(ResourceManager* theManager);
bool ExtractDelayLoad_ZombieNote1Resources(ResourceManager* theManager);
bool ExtractDelayLoad_ZombieNote2Resources(ResourceManager* theManager);
bool ExtractDelayLoad_ZombieNote3Resources(ResourceManager* theManager);
bool ExtractDelayLoad_ZombieNote4Resources(ResourceManager* theManager);
bool ExtractDelayLoad_ZombieNoteHelpResources(ResourceManager* theManager);
bool ExtractDelayLoad_ZombieNoteResources(ResourceManager* theManager);
bool ExtractDelayLoad_ZombiquariumResources(ResourceManager* theManager);
bool ExtractInitResources(ResourceManager* theManager);
bool ExtractLoaderBarResources(ResourceManager* theManager);
bool ExtractLoadingFontsResources(ResourceManager* theManager);
bool ExtractLoadingImagesResources(ResourceManager* theManager);
bool ExtractLoadingSoundsResources(ResourceManager* theManager);
bool ExtractResourcesByName(ResourceManager* theResourceManager, const char* theName);


// ==== M3-prep: extra globals referenced by game code (absent from trimmed resources) ====
extern Image* IMAGE_BACKGROUND6;
extern Image* IMAGE_BUGSPRAY;
extern Image* IMAGE_FLAG;
extern Image* IMAGE_GLOVE;
extern Image* IMAGE_GREENHOUSE;
extern Image* IMAGE_HOUSEDOOR_BOTTOM;
extern Image* IMAGE_HOUSEDOOR_TOP;
extern Image* IMAGE_MONEY_SIGN;
extern Image* IMAGE_MUSHROOM_GARDEN;
extern Image* IMAGE_REANIM_ZOMBIE_OUTERARM_UPPER2;
extern Image* IMAGE_REANIM_ZOMBIE_SCREENDOOR1;
extern Image* IMAGE_REANIM_ZOMBIE_SCREENDOOR2;
extern Image* IMAGE_REANIM_ZOMBIE_SCREENDOOR3;
extern Image* IMAGE_ROOFDOOR_BOTTOM;
extern Image* IMAGE_ROOFDOOR_TOP;
extern Image* IMAGE_SCARY_POT;
extern Image* IMAGE_SEEDBANK;
extern Image* IMAGE_SEEDBANK_BLANK;
extern Image* IMAGE_SEEDBANK_CONVEYORBELT;
extern Image* IMAGE_SEEDBANK_ICE;
extern Image* IMAGE_SEEDBANK_ZOMBIE;
extern Image* IMAGE_SEEDCHOOSER_BUTTON;
extern Image* IMAGE_SEEDS;
extern Image* IMAGE_SHOVEL;
extern Image* IMAGE_SHOVELBANK;
extern Image* IMAGE_SHOVEL_HI_RES;
extern Image* IMAGE_SLOT_MACHINE_BACKGROUND;
extern Image* IMAGE_SODBANK;
extern Image* IMAGE_STORE_SPEECHBUBBLE;
extern Image* IMAGE_STORE_SPEECHBUBBLE2;
extern Image* IMAGE_SUN;
extern Image* IMAGE_SUNBANK;
extern Image* IMAGE_SUNFLOWER_TROPHY;
extern Image* IMAGE_TACO;
extern Image* IMAGE_TOMBSTONES;
extern Image* IMAGE_TOMBSTONE_MOUNDS;
extern Image* IMAGE_TREEOFWISDOM;
extern Image* IMAGE_TREE_FOOD;
extern Image* IMAGE_TROPHY;
extern Image* IMAGE_TROPHY_HI_RES;
extern Image* IMAGE_WATERINGCAN;
extern Image* IMAGE_WHEELBARROW;
extern Image* IMAGE_ZENSHOPBUTTON;
extern Image* IMAGE_ZENSHOPBUTTON_HIGHLIGHT;
extern Image* IMAGE_ZOMBIEPOGO;
extern Image* IMAGE_ZOMBIE_NOTE_SMALL;
extern Image* IMAGE_ZOMBIQUARIUM;
extern _Font* FONT_COUNTER;
extern _Font* FONT_DWARVEN;
extern intptr_t SOUND_SHOOT;
extern intptr_t SOUND_ZOMBIESARE_COMING;

extern bool gNeedRecalcVariableToIdMap;

} // namespace Sexy
#endif // __RESOURCES_H__