// Minimal stub for Resources.cpp - defines IMAGE_* globals as NULL
// and Extract functions as stubs. Real image loading happens via
// ResourceManager on-demand.

#include "Resources.h"
#include "engine/ResourceManager.h"

// Define all Image* globals as NULL
namespace Sexy {

Image* IMAGE_BACKGROUND1 = NULL;
Image* IMAGE_BACKGROUND2 = NULL;
Image* IMAGE_BACKGROUND3 = NULL;
Image* IMAGE_BACKGROUND4 = NULL;
Image* IMAGE_BACKGROUND5 = NULL;
Image* IMAGE_BACKGROUND6 = NULL;
Image* IMAGE_BUGSPRAY = NULL;
Image* IMAGE_CHOCOLATE = NULL;
Image* IMAGE_FERTILIZER = NULL;
Image* IMAGE_FLAG = NULL;
Image* IMAGE_FOG = NULL;
Image* IMAGE_FOG_SOFTWARE = NULL;
Image* IMAGE_GLOVE = NULL;
Image* IMAGE_GREENHOUSE = NULL;
Image* IMAGE_HOUSEDOOR_BOTTOM = NULL;
Image* IMAGE_HOUSEDOOR_TOP = NULL;
Image* IMAGE_ICE = NULL;
Image* IMAGE_MONEY_SIGN = NULL;
Image* IMAGE_MUSHROOM_GARDEN = NULL;
Image* IMAGE_PHONOGRAPH = NULL;
Image* IMAGE_ROOFDOOR_BOTTOM = NULL;
Image* IMAGE_ROOFDOOR_TOP = NULL;
Image* IMAGE_SEEDBANK = NULL;
Image* IMAGE_SEEDBANK_BLANK = NULL;
Image* IMAGE_SEEDBANK_CONVEYORBELT = NULL;
Image* IMAGE_SEEDBANK_ICE = NULL;
Image* IMAGE_SEEDBANK_ZOMBIE = NULL;
Image* IMAGE_SHOVEL = NULL;
Image* IMAGE_SHOVELBANK = NULL;
Image* IMAGE_SLOT_MACHINE_BACKGROUND = NULL;
Image* IMAGE_SODBANK = NULL;
Image* IMAGE_SUN = NULL;
Image* IMAGE_PLANTSHADOW = NULL;
Image* IMAGE_SUNBANK = NULL;
Image* IMAGE_TREE_FOOD = NULL;
Image* IMAGE_TREEOFWISDOM = NULL;
Image* IMAGE_WATERINGCAN = NULL;
Image* IMAGE_WHEELBARROW = NULL;
Image* IMAGE_ZENSHOPBUTTON = NULL;
Image* IMAGE_ZENSHOPBUTTON_HIGHLIGHT = NULL;
Image* IMAGE_ZOMBIQUARIUM = NULL;
Image* IMAGE_SEEDCHOOSER_BUTTON = NULL;

// Coin / award images
Image* IMAGE_SEEDS = NULL;
Image* IMAGE_TROPHY = NULL;
Image* IMAGE_SUNFLOWER_TROPHY = NULL;
Image* IMAGE_CARKEYS = NULL;
Image* IMAGE_ALMANAC = NULL;
Image* IMAGE_SCARY_POT = NULL;
Image* IMAGE_TACO = NULL;
Image* IMAGE_ZOMBIE_NOTE_SMALL = NULL;
Image* IMAGE_PRESENT = NULL;
Image* IMAGE_PRESENTOPEN = NULL;
Image* IMAGE_MONEYBAG = NULL;
Image* IMAGE_MONEYBAG_HI_RES = NULL;
Image* IMAGE_TROPHY_HI_RES = NULL;
Image* IMAGE_SHOVEL_HI_RES = NULL;
Image* IMAGE_AWARDPICKUPGLOW = NULL;
Image* IMAGE_REANIM_COINGLOW = NULL;

// Reanimation image overrides
Image* IMAGE_REANIM_ZOMBIE_BUCKET1 = NULL;
Image* IMAGE_REANIM_ZOMBIE_BUCKET2 = NULL;
Image* IMAGE_REANIM_ZOMBIE_BUCKET3 = NULL;
Image* IMAGE_REANIM_ZOMBIE_SCREENDOOR1 = NULL;
Image* IMAGE_REANIM_ZOMBIE_SCREENDOOR2 = NULL;
Image* IMAGE_REANIM_ZOMBIE_SCREENDOOR3 = NULL;
Image* IMAGE_REANIM_ZOMBIE_LADDER_1 = NULL;
Image* IMAGE_REANIM_ZOMBIE_LADDER_1_DAMAGE1 = NULL;
Image* IMAGE_REANIM_ZOMBIE_LADDER_1_DAMAGE2 = NULL;
Image* IMAGE_REANIM_ZOMBIE_LADDER_5 = NULL;
Image* IMAGE_REANIM_ZOMBIE_JACKBOX_BOX = NULL;
Image* IMAGE_REANIM_ZOMBIE_DIGGER_PICKAXE = NULL;
Image* IMAGE_REANIM_ZOMBIE_FOOTBALL_HELMET = NULL;
Image* IMAGE_REANIM_ZOMBIE_FOOTBALL_HELMET2 = NULL;
Image* IMAGE_REANIM_ZOMBIE_FOOTBALL_HELMET3 = NULL;
Image* IMAGE_REANIM_WALLNUT_BODY = NULL;
Image* IMAGE_REANIM_WALLNUT_CRACKED1 = NULL;
Image* IMAGE_REANIM_WALLNUT_CRACKED2 = NULL;
Image* IMAGE_REANIM_TALLNUT_CRACKED1 = NULL;
Image* IMAGE_REANIM_TALLNUT_CRACKED2 = NULL;
Image* IMAGE_REANIM_GARLIC_BODY2 = NULL;
Image* IMAGE_REANIM_GARLIC_BODY3 = NULL;
Image* IMAGE_REANIM_PUMPKIN_DAMAGE1 = NULL;
Image* IMAGE_REANIM_PUMPKIN_DAMAGE3 = NULL;
Image* IMAGE_REANIM_COIN_SILVER_DOLLAR = NULL;
Image* IMAGE_REANIM_COIN_GOLD_DOLLAR = NULL;
Image* IMAGE_REANIM_DIAMOND = NULL;
Image* IMAGE_PLANTSHADOW2 = NULL;
Image* IMAGE_ZOMBIEPOGO = NULL;
Image* IMAGE_BLANK = NULL;
Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_ZOMBIE = NULL;
Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_DUCKXING = NULL;
Image* IMAGE_REANIM_ZOMBIE_GARGANTUAR_HEAD_REDEYE = NULL;
Image* IMAGE_REANIM_ZOMBIE_PAPER_MADHEAD = NULL;
Image* IMAGE_REANIM_ZOMBIE_FOOTBALL_LEFTARM_UPPER2 = NULL;
Image* IMAGE_REANIM_ZOMBIE_PAPER_LEFTARM_UPPER2 = NULL;
Image* IMAGE_REANIM_ZOMBIE_OUTERARM_UPPER2 = NULL;

// Projectile images
Image* IMAGE_REANIM_COBCANNON_COB = NULL;
Image* IMAGE_PROJECTILEPEA = NULL;
Image* IMAGE_PROJECTILESNOWPEA = NULL;
Image* IMAGE_PROJECTILECACTUS = NULL;
Image* IMAGE_PROJECTILE_STAR = NULL;
Image* IMAGE_PUFFSHROOM_PUFF1 = NULL;
Image* IMAGE_REANIM_ZOMBIE_CATAPULT_BASKETBALL = NULL;
Image* IMAGE_REANIM_CABBAGEPULT_CABBAGE = NULL;
Image* IMAGE_REANIM_CORNPULT_KERNAL = NULL;
Image* IMAGE_REANIM_CORNPULT_BUTTER = NULL;
Image* IMAGE_REANIM_MELONPULT_MELON = NULL;
Image* IMAGE_REANIM_WINTERMELON_PROJECTILE = NULL;
Image* IMAGE_PEA_SHADOWS = NULL;

// GridItem images
Image* IMAGE_PLANTSPEECHBUBBLE = NULL;
Image* IMAGE_BRAIN = NULL;
Image* IMAGE_TOMBSTONES = NULL;
Image* IMAGE_TOMBSTONE_MOUNDS = NULL;
Image* IMAGE_CRATER = NULL;
Image* IMAGE_CRATER_WATER_NIGHT = NULL;
Image* IMAGE_CRATER_WATER_DAY = NULL;
Image* IMAGE_CRATER_ROOF_LEFT = NULL;
Image* IMAGE_CRATER_ROOF_CENTER = NULL;
Image* IMAGE_CRATER_FADING = NULL;

// TitleScreen and loading images
Image* IMAGE_TITLESCREEN = NULL;
Image* IMAGE_PARTNER_LOGO = NULL;
Image* IMAGE_POPCAP_LOGO = NULL;
Image* IMAGE_LOADBAR_DIRT = NULL;
Image* IMAGE_LOADBAR_GRASS = NULL;
Image* IMAGE_PVZ_LOGO = NULL;
Image* IMAGE_REANIM_SODROLLCAP = NULL;

} // namespace Sexy

// Extract functions stubs - always return true without loading
bool Sexy::ExtractResourcesByName(ResourceManager* theResourceManager, const char* theName)
{
    (void)theResourceManager;
    (void)theName;
    return true;
}

bool Sexy::ExtractInitResources(ResourceManager* theResourceManager)
{
    (void)theResourceManager;
    // Images are loaded on-demand by ResourceManager::GetImage
    return true;
}

bool Sexy::ExtractLoaderBarResources(ResourceManager* theResourceManager)
{
    (void)theResourceManager;
    return true;
}
